here=$(dirname $(readlink -f ${BASH_SOURCE[0]}))

export AMOEBASEGMENTER_ROOT_DIR="${here}"
export AMOEBASEGMENTER_DATA_DIR="${AMOEBASEGMENTER_ROOT_DIR}/data"
export AMOEBASEGMENTER_SCRIPTS_DIR="${AMOEBASEGMENTER_ROOT_DIR}/scripts"
export AMOEBASEGMENTER_SOURCE_DIR="${AMOEBASEGMENTER_ROOT_DIR}/code/amoeba_segmenter"
export AMOEBASEGMENTER_LOADED=1
