#!/usr/bin/env bash
### SLURM HEADER
#SBATCH --job-name=bfconvert
#SBATCH --output=bfconvert-%j.log
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=bill.flynn@jax.org

#SBATCH --account=singlecell
#SBATCH --partition=batch
#SBATCH --qos=normal
#SBATCH --time=3:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=4GB

#SBATCH --export=ALL
### SLURM HEADER

localcores=${SLURM_CPUS_PER_TASK}

cd ${SLURM_SUBMIT_DIR}

if [ ! -z ${BFTOOLS_PATH} ]; then
    echo "Local bftools path provided, will try to use instead of apptainer"
    bfconvert="${BFTOOLS_PATH}/bfconvert"
    showinf="${BFTOOLS_PATH}/showinf"

    local_found=0
    if [ -f $bfconvert ]; then
        local_found=1
    fi
fi

if [ $local_found -eq 0 ]; then
    echo "Local bftools path not found or not provided"
    echo "Falling back to containerization"
    {
        module load singularity
    } || {
         module load apptainer
         # apptainer creates an alias for singularity
         # so "singularity" as a command should work 
    }
    
    bfconvert="singularity run ${AMOEBASEGMENTER_ROOT_DIR}/containers/img/bftools-6.13.0.sif bfconvert"
    showinf="singularity run  ${AMOEBASEGMENTER_ROOT_DIR}/containers/img/bftools-6.13.0.sif showinf"
fi


infile="${1}"

if [ -z "${infile}" ]; then
    echo "must supply a file!" >&2
    exit 1
fi

echo "File: ${infile}"
nseries=$($showinf "$infile" -nopix | grep 'Series count = ' | grep -Eo '[0-9]+')
echo "N series: $nseries"
for i in $(seq 0 $((nseries - 1))); 
do
  $bfconvert -overwrite -series $i "${infile}" "${infile}_${i}.ome.tiff"
done
